version: '3.8'

services:
  backend:
    build: .
    container_name: nestjs-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
